Repository Haato3o/HunterPie, pull requests merged in 2020-10, with the labels that each got.

#99 ko-kr.xml localisation updated for Fatalis update.
  HunterPie/Languages/ko-kr.xml
Labels: HunterPie: Localization

#102 Cleanup code
  HunterPie/Core/Client/UserSettings.cs
  HunterPie/Core/Craft/Recipe.cs
  HunterPie/Core/Craft/Recipes.cs
  HunterPie/Core/Enums/AilmentType.cs
  HunterPie/Core/Enums/Helper.cs
  HunterPie/Core/Events/AbnormalityEventArgs.cs
  HunterPie/Core/Events/FertilizerEventArgs.cs
  HunterPie/Core/Events/HarvestBoxEventArgs.cs
  HunterPie/Core/Events/InventoryUpdatedEventArgs.cs
  HunterPie/Core/Events/MantleEventArgs.cs
  HunterPie/Core/Game.cs
  HunterPie/Core/Input/Hotkey.cs
  HunterPie/Core/Integrations/DataExporter/Exporter.cs
  HunterPie/Core/Local/Abnormality.cs
  HunterPie/Core/Local/AbnormalityData.cs
  HunterPie/Core/Local/Jobs/HeavyBowgun.cs
  HunterPie/Core/Party/Party.cs
  HunterPie/GUI/Widgets/Abnormality Widget/Parts/AbnormalityControl.xaml.cs
  HunterPie/GUI/Widgets/ClassWidget/ClassWidgetContainer.xaml.cs
  HunterPie/GUI/Widgets/DPSMeter/Meter.xaml.cs
  HunterPie/GUI/Widgets/DPSMeter/Parts/PartyMember.xaml.cs
  HunterPie/GUI/Widgets/Harvest Box/HarvestBox.xaml.cs
  HunterPie/GUI/Widgets/Monster Widget/Parts/MonsterAilment.xaml.cs
  HunterPie/GUIControls/Custom Controls/MinimalHealthBar.xaml.cs
  HunterPie/GUIControls/Custom Controls/PositionControl.xaml.cs
  HunterPie/GUIControls/Plugins.xaml.cs
  HunterPie/GUIControls/settingsWindow.xaml.cs
  HunterPie/HunterPie.Plugins/PluginManager.cs
  HunterPie/HunterPie.Plugins/PluginUpdate.cs
  HunterPie/clean.py
  docs/Plugins/game.md
Labels: Cleanup

#106 Add monster health info hiding setting
  HunterPie/Core/Client/UserSettings.cs
  HunterPie/GUI/Widgets/Monster Widget/MonsterHealth.xaml.cs
  HunterPie/GUIControls/NewSettingsWindow.xaml
  HunterPie/GUIControls/Settings.xaml.cs
  HunterPie/Hunterpie.xaml.cs
  HunterPie/Languages/en-us.xml
  HunterPie/Languages/es-es.xml
Labels: Enhancements
